# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 571c97ce6827904a068242ceefb79a84294c7fa8ad312d748c36db3a7d1e8261f678e2ed2a1300584b5752dd4716a2a252ac991036db5d102cdaeb2daa39cec9

test:
  secret_key_base: 177f94efc3b2f16faff80c7a5d6e37050d7e9e27b71357bd9c20d42b1a85a42f69546c5bf30cfa64950ffcf33dbc5f0ffd0346d35841b31317fb06350d00e7ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
